# Generated by Django 5.1.4 on 2024-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_pdf', models.FileField(upload_to='documents/')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Blog', 'Blog'), ('Report', 'Report')], default='Blog', max_length=50, null=True)),
                ('managerId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
