# Generated by Django 4.2.17 on 2024-12-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='category',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('project_progress', 'Project Progress'), ('remote_work', 'Remote Work')], default='Blog', max_length=50, null=True),
        ),
    ]
