# Generated by Django 4.2.17 on 2024-12-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_system', '0002_alter_documents_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='isApprouved',
            field=models.BooleanField(default=False),
        ),
    ]
