# Generated by Django 4.2.17 on 2024-12-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_system', '0003_documents_isapprouved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='isApprouved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
